title: Computational resource
description: A central resource page to access the programs, pipelines and scripts developed within the campus microbiome community
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
